### PR TITLE
Show Group description in Dashboard.

### PR DESCRIPTION
**Pull request by matinieves**
Also:
 * Change Groups description type to text.

related to #261.

### CODE REVIEW

**Comment by rabble** [comment]
This requires a migration you can't just go back in and edit schema.rb ;-)

**Comment by matinieves** [comment]
Do you mean [this](https://github.com/advocacycommons/advocacycommons/pull/272/files#diff-0172a73f2a9cad3574be16757852d89c)?  ;-)

**Comment by rabble** [comment]
Yeah i mean: [https://github.com/advocacycommons/advocacycommons/commit/88583ad725413478f519790f83b85508ac9ba12e#diff-1acd2e7e27a227829d5d14a91c863bb6](this), where you don't commit a migration file, just are changing schema.rb... i'm pretty sure you forgot to add the migration. ;-)

**Comment by matinieves** [comment]
Yes I added the migration file:

image

Take a look to the changed files.

**Comment by rabble** [comment]
I plead blindness

**Pull request merged**
