### PR TITLE
[#465] clarify dev env steps in readme

### LINKED ISSUE #465: TECH TASK: clarify README instructions for dev env setup [2]
## Acceptance Criteria

* new contributor can follow instructions in README to setup dev env on either Mac or Debian without further clarification

## Out of Scope

* dockerizing anything

### PR DESCRIPTION
**Pull request by aguestuser**
Resolves #465 and fulfills its acceptance criteria.

## Implementation notes

* list all dependencies and version numbers
* translate all instructions into bash commands
* provide variations for Mac and Debian where applicable
* side-effect: add password for local dev db
  (necessary to run on aguestuser's postgres config)

### CODE REVIEW

**Comment by aguestuser** [comment]
@rabble , @Matt-Holland , not sure who should review this, so take your pick!

Note: de-scoped dockerization from this card and put it into #469 .

**Comment by Matt-Holland** [comment]
ERROR on line 54 of bin/install:
`source ./bin/affinity/env`
should be:
`source ./bin/env`

**Comment by aguestuser** [comment]
@Matt-Holland okay to merge this? it will be live for all of one day while i work on completing #469 

(but in the meantime, it will be nicer!)

**Comment by Matt-Holland** [comment]
Yes, merge is ok by me.

**Pull request merged**
