### PR TITLE
Add seeds.

### PR DESCRIPTION
**Pull request by agustinrhcp**
#148

### CODE REVIEW

**Comment by rabble** [comment]
This isn't the right API key to use. We need one which points to an AN group which as a few members, not the top level one which includes all members and events.

**Comment by agustinrhcp** [comment]
@rabble Makes sense,  that's why I asked what key to use in the issue (: 

Could you give me the correct one?

**Comment by Matt-Holland** [comment]
@rabble this is rejected. I tested by attempting to log in to http://dev-advocacycommons.herokuapp.com/admin/login with the email/password combinations shown in the commit, but got "Invalid Email or Password" each time.

**Comment by rabble** [comment]
You test this on Review Apps NOT DEV....

**Pull request merged**
