### PR TITLE
Facebook integration

### PR DESCRIPTION
**Pull request by matinieves**
Related to #159 and #160 

@rabble I added the Identity model, so now we can save all the information of third-party providers for a User there. With that change, in the future, we can easily add more providers.

### CODE REVIEW

**Comment by matinieves** [comment]
@rabble , @Matt-Holland. I think we will need a testing Facebook account for Affinity. With that we can create an OAuth application in `developer.facebook.com` and any of us can add the different `callback_url` for any environment.

**Comment by matinieves** [comment]
About #160 now we only see the list of matched events (if any). I'm currently working on selecting one from the list and continue with the expected flow

**Comment by rabble** [comment]
Looks like the tests fail, i'm not sure if it's my config or the code base in general...


# Running:

F

Failure:
ImportsControllerTest#test_get_#find [/Users/rabble/code/advocacycommons/test/controllers/imports_controller_test.rb:28]:
Expected: 1
  Actual: 0


bin/rails test test/controllers/imports_controller_test.rb:7

**Comment by rabble** [comment]
Failing tests and the rails app dies on login... 

ArgumentError in ActiveAdmin::Devise::SessionsController#create
A copy of ApplicationController has been removed from the module tree but is still active!

Extracted source (around line #51):
49
50
51
52
53
54
              

  def current_ability
    @current_ability ||= Ability.new(current_user, current_group)
  end

  def json_request?

Rails.root: /Users/rabble/code/advocacycommons

Application Trace | Framework Trace | Full Trace
app/controllers/application_controller.rb:51:in `current_ability'
app/controllers/application_controller.rb:24:in `after_sign_in_path_for'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"kE8DEmhRZ4Omz+pBxXvQUbCn571Cy/hXxt4iRM113vb9hD1ZYJG/L05nsS5XlAPuujAsBGtuTYSsgzqxP/QnOA==",
 "person"=>{"email"=>"organizer@member.com", "password"=>"[FILTERED]", "remember_me"=>"0"},
 "commit"=>"Login"}
Toggle session dump
Toggle env dump
Response

Headers:

None
x
>>   

14:34 $ rake
Run options: --seed 10006

# Running:

..............................................................F

Failure:
ImportsControllerTest#test_get_#find [/Users/rabble/code/advocacycommons/test/controllers/imports_controller_test.rb:28]:
Expected: 1
  Actual: 0


bin/rails test test/controllers/imports_controller_test.rb:7

.....................................................F

Failure:
EventTest#test_.start [/Users/rabble/code/advocacycommons/test/models/event_test.rb:74]:
--- expected
+++ actual
@@ -1 +1 @@
-[#<Event id: 15, origin_system: nil, name: nil, title: nil, description: nil, summary: nil, browser_url: nil, osdi_type: nil, ticket_levels: nil, featured_image_url: nil, total_accepted: nil, total_tickets: nil, total_amount: nil, status: nil, instructions: nil, start_date: "2017-05-30 00:00:00", end_date: nil, all_day_date: nil, all_day: nil, capacity: nil, guests_can_invite_others: nil, transparency: nil, visibility: nil, creator_id: nil, organizer_id: nil, modified_by_id: nil, ticket_levels_id: nil, address_id: nil, created_at: "2017-05-30 21:35:27", updated_at: "2017-05-30 21:35:27", share_url: nil, total_shares: 0, identifiers: ["advocacycommons:15"]>]
+#<ActiveRecord::Relation []>



bin/rails test test/models/event_test.rb:69

...............

Finished in 26.535561s, 4.9745 runs/s, 13.5290 assertions/s.

132 runs, 359 assertions, 2 failures, 0 errors, 0 skips

**Comment by agustinrhcp** [comment]
Moved to facebook-integration-2

**Pull request closed without merging**
