### PR TITLE
Add active admin permission.

### PR DESCRIPTION
**Pull request by agustinrhcp**
#105 
Has migrations.

### CODE REVIEW

**Comment by rabble** [comment]
Hey Agustin,

If somebody just goes to /admin/login and they aren't an admin where does it redirect them? I think it'll got to a permission denied page instead of their group / dashboard which is what it should i think... basically what happens if they go directly to login, where does it take them?

**Comment by agustinrhcp** [comment]
Good question. I think they'll be shown a 404 page. What should be the expected behavior?

**Comment by agustinrhcp** [comment]
Ok, I fixed to do the following.
When login in if the user is admin, it gets redirected to `admin/dasboard`, if not to `/events`.
If the non admin is already logged in and tries to access a `/admin/` url he will get a 404 page.

**Comment by rabble** [comment]
So no tests, and when i tried it as a non-admin user, it let me get to the admin dashboard. So, this didn't work....

**Comment by agustinrhcp** [comment]
Weird, I tested it and worked fine. I'll write some tests for the login

**Comment by agustinrhcp** [comment]
I added tests for the issue you are facing and it seems to work, are you sure you changed the admin attribute to false?

**Comment by rabble** [comment]
13:14:21 web.1    | Started POST "/admin/login" for ::1 at 2017-05-10 13:14:21 -0700
13:14:21 web.1    | Processing by ActiveAdmin::Devise::SessionsController#create as HTML
13:14:21 web.1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"jCQ/222b0FO3vGxuHUnJvcC9yroxAqtCCV8HUAp2OIhz4VCkoItrVXSIFvJE0n7f0EG4XLyv3FO3hEfQwRvyRA==", "person"=>{"email"=>"evan@henshaw-plath.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Login"}
13:14:21 web.1    | Geokit is using the domain: localhost
13:14:21 web.1    |   SQL (34.4ms)  SELECT  DISTINCT "people"."id", "people"."id" AS alias_0 FROM "people" LEFT OUTER JOIN "email_addresses" ON "email_addresses"."person_id" = "people"."id" WHERE "email_addresses"."address" = $1 ORDER BY "people"."id" ASC LIMIT $2  [["address", "evan@henshaw-plath.com"], ["LIMIT", 1]]
13:14:21 web.1    |   SQL (45.0ms)  SELECT "people"."id" AS t0_r0, "people"."array" AS t0_r1, "people"."family_name" AS t0_r2, "people"."given_name" AS t0_r3, "people"."additional_name" AS t0_r4, "people"."honorific_prefix" AS t0_r5, "people"."honorific_suffix" AS t0_r6, "people"."gender" AS t0_r7, "people"."gender_identity" AS t0_r8, "people"."party_identification" AS t0_r9, "people"."source" AS t0_r10, "people"."ethnicities" AS t0_r11, "people"."languages_spoken" AS t0_r12, "people"."birthdate" AS t0_r13, "people"."employer" AS t0_r14, "people"."custom_fields" AS t0_r15, "people"."created_at" AS t0_r16, "people"."updated_at" AS t0_r17, "people"."encrypted_password" AS t0_r18, "people"."reset_password_token" AS t0_r19, "people"."reset_password_sent_at" AS t0_r20, "people"."remember_created_at" AS t0_r21, "people"."sign_in_count" AS t0_r22, "people"."current_sign_in_at" AS t0_r23, "people"."last_sign_in_at" AS t0_r24, "people"."current_sign_in_ip" AS t0_r25, "people"."last_sign_in_ip" AS t0_r26, "people"."identifiers" AS t0_r27, "people"."admin" AS t0_r28, "email_addresses"."id" AS t1_r0, "email_addresses"."primary" AS t1_r1, "email_addresses"."address" AS t1_r2, "email_addresses"."address_type" AS t1_r3, "email_addresses"."status" AS t1_r4, "email_addresses"."person_id" AS t1_r5, "email_addresses"."created_at" AS t1_r6, "email_addresses"."updated_at" AS t1_r7 FROM "people" LEFT OUTER JOIN "email_addresses" ON "email_addresses"."person_id" = "people"."id" WHERE "email_addresses"."address" = $1 AND "people"."id" = 27 ORDER BY "people"."id" ASC  [["address", "evan@henshaw-plath.com"]]
13:14:21 web.1    | Completed 401 Unauthorized in 96ms (ActiveRecord: 79.4ms)
13:14:21 web.1    | 
13:14:21 web.1    | 
13:14:21 web.1    | Processing by ActiveAdmin::Devise::SessionsController#new as HTML
13:14:21 web.1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"jCQ/222b0FO3vGxuHUnJvcC9yroxAqtCCV8HUAp2OIhz4VCkoItrVXSIFvJE0n7f0EG4XLyv3FO3hEfQwRvyRA==", "person"=>{"email"=>"evan@henshaw-plath.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Login"}
13:14:21 web.1    | Geokit is using the domain: localhost
13:14:21 web.1    |   Rendering /Users/rabble/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0.pre4/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out
13:14:21 web.1    |   Rendered /Users/rabble/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0.pre4/app/views/active_admin/devise/shared/_links.erb (6.6ms)
13:14:21 web.1    |   Rendered /Users/rabble/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0.pre4/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (63.2ms)
13:14:22 web.1    | Completed 200 OK in 778ms (Views: 540.2ms | ActiveRecord: 0.0ms)
13:14:22 web.1    | 
13:14:22 web.1    | 

So right now it takes you and logs you in, says you don't have access to /admin/ and then redirects you back to the login page saying login failed. #fail

**Comment by Matt-Holland** [comment]
related ticket tested and passed on Dev

**Pull request merged**
