### PR TITLE
[issue 408] - Add facebook button design

### PR DESCRIPTION
**Pull request by nice00xt**
screen shot 2017-11-22 at 9 35 33 am

related to #408

### CODE REVIEW

**Comment by Matt-Holland** [comment]
This looks right to me, let's deploy it.

**Comment by nice00xt** [comment]
I noticed that the password an sign-up views, are separate views so,
I have to set the css design for the rest of the login pages 
- sign up
- password

**Comment by nice00xt** [comment]
@Matt-Holland Done can you take a review please?

**Comment by Matt-Holland** [comment]
This works correctly on local dev. Let's deploy.

**Pull request merged**
