### PR TITLE
Memberships role

### PR DESCRIPTION
**Pull request by matinieves**
related to #82

### CODE REVIEW

**Comment by rabble** [comment]
This migration doesn't work.
✔ ~/code/advocacycommons [matinieves-membership_roles L|✚ 1⚑ 27] 
19:23 $ rake db:migrate
== 20170503191123 ChangeMembershipsRoleTypeToInteger: migrating ===============
-- change_column(:memberships, :role, "integer USING CAST(role AS integer)", {:default=>0})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "member"
: ALTER TABLE "memberships" ALTER COLUMN "role" TYPE integer USING CAST(role AS integer)
/Users/rabble/code/advocacycommons/db/migrate/20170503191123_change_memberships_role_type_to_integer.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "member"
: ALTER TABLE "memberships" ALTER COLUMN "role" TYPE integer USING CAST(role AS integer)
/Users/rabble/code/advocacycommons/db/migrate/20170503191123_change_memberships_role_type_to_integer.rb:3:in `change'
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "member"
/Users/rabble/code/advocacycommons/db/migrate/20170503191123_change_memberships_role_type_to_integer.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
✘-1 ~/code/advocacycommons [matinieves-membership_roles L|✚ 1⚑ 27] 
19:23 $

**Comment by matinieves** [comment]
Do you see that error when trying to run the migration on the test environment? In that case you need to `rake db:test:prepare` instead of `rake db:migrate ENV='test'`.

It seems to be that you have some memberships role with value 'member' that cannot be cast as integer.

**Comment by rabble** [comment]
Hey, your migrations need to work.

17:25 $ rake db:migrate ENV='test'
== 20170503191123 ChangeMembershipsRoleTypeToInteger: migrating ===============
-- change_column(:memberships, :role, "integer USING CAST(role AS integer)", {:default=>0})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "member"
: ALTER TABLE "memberships" ALTER COLUMN "role" TYPE integer USING CAST(role AS integer)
/Users/rabble/code/advocacycommons/db/migrate/20170503191123_change_memberships_role_type_to_integer.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "member"
: ALTER TABLE "memberships" ALTER COLUMN "role" TYPE integer USING CAST(role AS integer)
/Users/rabble/code/advocacycommons/db/migrate/20170503191123_change_memberships_role_type_to_integer.rb:3:in `change'
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "member"
/Users/rabble/code/advocacycommons/db/migrate/20170503191123_change_memberships_role_type_to_integer.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by matinieves** [comment]
Please test it again. Make sure both databases have the default value for the rol column:

image

If not you can run 
`RAILS_ENV=test rake db:rollback STEP=steps_needed_to_migration` for test db
`rake db:rollback STEP=steps_needed_to_migration` for test db

**Pull request merged**
